### ISSUE TITLE
Donation.PaymentStatus is not updated if multiple payment tries happens

### ISSUE THREAD

**Issue by guerrerotook** [banco-alimentar/alimentestaideia.pt#584] opened 2021-12-22 16:21 UTC
If the user make multiples attempts of paying with multiple payment methods, the filed Donation.PaymentStatus is not updated.

**Comment by tiagonmas** [comment] 2022-11-30 11:37
It seems this issue is still happening. 
In this campaign (past week), we have 3 donations that have more than one confirmed payment and completed:


```
SELECT        TOP (100) dbo.Donations.Id, COUNT(dbo.Donations.ConfirmedPaymentId) AS TotalConfirmedPayment, Max(DonationDate),COUNT(Completed) TotalCompleted
FROM            dbo.Donations LEFT OUTER JOIN
                         dbo.Payments ON dbo.Donations.Id = dbo.Payments.DonationId
GROUP BY dbo.Donations.Id
HAVING COUNT(Completed) > 1
ORDER BY Max(DonationDate) DESC
```

The Payments below, refer more than one sucessful payment for the same Donation
```
select * from [dbo].[Payments] where DonationId=16086
select * from [dbo].[Payments] where DonationId=16269
select * from [dbo].[Payments] where DonationId=18370
```

**Comment by tiagonmas** [comment] 2023-05-09 10:26
This is still happening. Here are some transactions from current campaign that have more than one payment
`select * from [dbo].[Payments] where DonationId in (24050,23731,21713)`

**Comment by tiagonmas** [comment] 2023-05-09 16:16
@guerrerotook  can you take a look at this when you have time ?

**Comment by tiagonmas** [comment] 2023-10-18 11:04
Another way to check the records impacted by this:
```
SELECT (Select count(id) from Payments where DonationId=Donations.id) as NumPayments,dbo.Donations.Id, dbo.Donations.DonationDate, dbo.Donations.PaymentStatus, dbo.Donations.ConfirmedPaymentId
FROM  dbo.Donations 
WHERE (dbo.Donations.ConfirmedPaymentId IS NOT NULL) AND (dbo.Donations.PaymentStatus = 4)
Order by NumPayments asc
```

**Comment by tiagonmas** [comment] 2023-10-18 11:04
seems to be the same issue as #735

**Comment by tiagonmas** [comment] 2023-10-19 17:16
Updated database to fix the past 73 records that had this issue
```
UPDATE dbo.Donations 
   SET dbo.Donations.PaymentStatus = 1
	 WHERE dbo.Donations.Id IN 
		(
			SELECT        distinct(dbo.Payments.DonationId)
				FROM            dbo.Payments RIGHT OUTER JOIN dbo.Donations ON dbo.Payments.DonationId = dbo.Donations.Id
				WHERE (dbo.Donations.PaymentStatus = 4) AND (NOT (dbo.Donations.ConfirmedPaymentId IS NULL))
		)
```

**Comment by tiagonmas** [comment] 2024-12-03 09:53
closing as it is no longer happening

**Closed by tiagonmas** 2024-12-03 09:53 UTC
Labels: bug, very.high.priority
